name: Sync with Crowdin

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

jobs:
  sync-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - List directory contents
        run: ls -la

      - name: Upload source language to Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          download_translations: false
          push_translations: false

      - name: Create pull request for new translations
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          download_translations: true
          push_translations: true
